### ISSUE TITLE
Update to NC 25

### ISSUE THREAD

**Issue by kralan** [mtierltd/timetracker#192]
With NC 25, only the menu is displayed, no client area.
Please update TimeTracker to work with NC 25.

**Comment by annego15** [comment]
I found a hotfix. Replace the content of the file `nextcloud/app/custom_apps/timetracker/templates/index.php` With the following:

```script('timetracker', "kingtable");
script('timetracker', "moment.min");
script('timetracker', "daterangepicker.min");
script('timetracker', "tabulator");
script('timetracker', "Chart.min");
script('timetracker', "select2.min");
style('timetracker', "kingtable");
style('timetracker', "daterangepicker");
style('timetracker', "tabulator");
*/
//style('timetracker', "select2");

//style('files', 'files');
style('timetracker', 'all');
style('timetracker', 'style');
script('timetracker', $script);

?>

<div id="app-navigation">
	<?php print_unescaped($this->inc('navigation/index')); ?>
	<?php print_unescaped($this->inc('settings/index')); ?>
</div>
<div id="app-content" style="padding: 20px;">
	<div id="app-content-wrapper">
		<?php print_unescaped($this->inc($appPage)); ?>
	</div>
</div>

```

It would be wise to update the app, but I will not create a pull request as I don't know wether it would break the previous versions.

**Comment by kralan** [comment]
Thank you for your input,, @annego15 !
I tried your solution and it worked for me.

A few observations:
- The first few lines of the file seem to be missing from your code snippet.
- The file resided in `nextcloud/apps/timetracker/templates` in my installation.
- The only difference I could find in your code is the additional ` style="padding: 20px;"` and the removed `<div id="app">`. Is this correct?
- There are still some minor visual glitches like the missing icon on the tag search button in the timeline view.

**Comment by annego15** [comment]
Thanks @kralan!

I edited my code to now include all the lines and changed the path. However I checked again, in my installation the path is definitely different from yours. It might be due to the fact, that I use docker.

Your observation is correct, I removed the `<div id="app">` as it was messing with the overlaying flex div and added the padding because it looks better that way. The padding is definitely something that only became necessary with the new layout, so it would only be needed in NC 25. About the div, I'm not sure if the app would without it work on a lower version of Nextcloud.
