### ISSUE TITLE
App doesn't follow Nextcloud design guidelines

### ISSUE THREAD

**Issue by rspencer01** [mtierltd/timetracker#37]
There are some recommended [design guidelines](https://docs.nextcloud.com/server/latest/developer_manual//design/index.html) for nextcloud apps that I think this app would greatly benefit from following.

An easy first step would be replacing the tables in tags, clients and projects with [content lists](https://docs.nextcloud.com/server/latest/developer_manual//design/list.html).  I think this should get rid of `tabulator.js` entirely.

I'm happy to try hack away at this over the next few months when I get some spare time.

**Comment by reinerj** [comment]
Hi,

you are welcome to do so and pachtches will accepted

Thanks
Reiner

**Comment by rspencer01** [comment]
Of course the ultimate solution would be to move to a vue powered app structure.

I think for the moment though, that is a little ambitious.  Simply bringing the look and feel in line with the rest of the ecosystem should take enough time as it is.

**Comment by digger-bw** [comment]
Hi, 

i've tried to work on this issue. Until now i've made a much better progress then i've expected. Because im not sure whether i get i to work i've started by using an VUEJS App-Example-Template and migrate the corresponding part to this together with new/modified parts.

If you guys want i can give you the ready result but. What would be the best way? A patch will result in a nearly complete change. What happens in this case with your already started works?

Let me how whether and when: How you are interested.

Regards Jan

**Comment by reinerj** [comment]
Hi,

thanks for the update. We will come back to you shortly with additional feedback.

Regards
Reiner

**Comment by rspencer01** [comment]
My edits don't really do the app justice: I ran into more problems than I expected without Vue.   I'm happy for yours to supersede them

**Comment by digger-bw** [comment]
We'll see at the end ... i'm working  on it also in my spare time ... so it needs some time 

Furthermore it need a little bit input: what's the Intension / difference between timeline timeline admin?  
Is there a reason that the report didn't show the time of the entry? 
What is the Intension to sort the timer list in this way?

**Comment by puthre** [comment]
I will close this item for now. Will reconsider when somebody has a pull request.
